//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.UA.Model.Designer.ImportExport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAS.UA.Model.Designer.ImportExport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportFromOPCDAMenuItem.
        /// </summary>
        internal static string CreateFromOPCDAMenuItemName {
            get {
                return ResourceManager.GetString("CreateFromOPCDAMenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From OPC DA ....
        /// </summary>
        internal static string CreateFromOPCDAMenuItemText {
            get {
                return ResourceManager.GetString("CreateFromOPCDAMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It allows user to create model representing OPC DA using dictionary (.odic)
        ///file created by the OPC Viewer..
        /// </summary>
        internal static string CreateFromOPCDAMenuItemToolTip {
            get {
                return ResourceManager.GetString("CreateFromOPCDAMenuItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportMenuItem.
        /// </summary>
        internal static string CreateImportMenuItemName {
            get {
                return ResourceManager.GetString("CreateImportMenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string CreateImportMenuItemText {
            get {
                return ResourceManager.GetString("CreateImportMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It imports models from external formats..
        /// </summary>
        internal static string CreateImportMenuItemToolTip {
            get {
                return ResourceManager.GetString("CreateImportMenuItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse name.
        /// </summary>
        internal static string ExportTool_BrowseName {
            get {
                return ResourceManager.GetString("ExportTool_BrowseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model documentation.
        /// </summary>
        internal static string ExportTool_DocumentTitle {
            get {
                return ResourceManager.GetString("ExportTool_DocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving process failed becasue of the problem with a file! (details: {0}).
        /// </summary>
        internal static string ExportTool_ExportGeneralError_with_details {
            get {
                return ResourceManager.GetString("ExportTool_ExportGeneralError_with_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving of the file failed becasue of problem in serializing process!.
        /// </summary>
        internal static string ExportTool_ExportSerializationProblem {
            get {
                return ResourceManager.GetString("ExportTool_ExportSerializationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving of the file succeeded! Click OK if you want to open created file or Cancel to return to program.
        /// </summary>
        internal static string ExportTool_ExportSucceded {
            get {
                return ResourceManager.GetString("ExportTool_ExportSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not saved!.
        /// </summary>
        internal static string ExportTool_FileWasNotSaved {
            get {
                return ResourceManager.GetString("ExportTool_FileWasNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAbstract.
        /// </summary>
        internal static string ExportTool_IsAbstract {
            get {
                return ResourceManager.GetString("ExportTool_IsAbstract", resourceCulture);
            }
        }
    }
}
