//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.UA.Model.Designer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAS.UA.Model.Designer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AdddItem {
            get {
                object obj = ResourceManager.GetObject("AdddItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowLeft32 {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowRight32 {
            get {
                object obj = ResourceManager.GetObject("ArrowRight32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASMDbanner {
            get {
                object obj = ResourceManager.GetObject("ASMDbanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://commsvr-com.github.io/Documentation/ModelDesigner.
        /// </summary>
        internal static string AsmdHelp {
            get {
                return ResourceManager.GetString("AsmdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/tabid/535/Default.aspx.
        /// </summary>
        internal static string AsmdVersionsComparison {
            get {
                return ResourceManager.GetString("AsmdVersionsComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Creation of Address Space; Please wait ....
        /// </summary>
        internal static string BrowseViewObserver_pleasewait_step1 {
            get {
                return ResourceManager.GetString("BrowseViewObserver_pleasewait_step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Preparation of the browse tree view; Please wait ....
        /// </summary>
        internal static string BrowseViewObserver_pleasewait_step2 {
            get {
                return ResourceManager.GetString("BrowseViewObserver_pleasewait_step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Build {
            get {
                object obj = ResourceManager.GetObject("Build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***********************************
        ///Building the solution ...
        ///***********************************.
        /// </summary>
        internal static string Build_all {
            get {
                return ResourceManager.GetString("Build_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build project.
        /// </summary>
        internal static string Build_Caption {
            get {
                return ResourceManager.GetString("Build_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK when SDK code generator has finished its work..
        /// </summary>
        internal static string Build_click_ok_when_build_has_finished {
            get {
                return ResourceManager.GetString("Build_click_ok_when_build_has_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build ended at: {0}..
        /// </summary>
        internal static string Build_ended_at {
            get {
                return ResourceManager.GetString("Build_ended_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------ Building project: {0}. ------.
        /// </summary>
        internal static string Build_project_name {
            get {
                return ResourceManager.GetString("Build_project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Project has been built successfully. *.
        /// </summary>
        internal static string Build_project_ok {
            get {
                return ResourceManager.GetString("Build_project_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build started at: {0}..
        /// </summary>
        internal static string Build_started_at {
            get {
                return ResourceManager.GetString("Build_started_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !ERROR!
        ///The following has occurred:
        ///{0}
        ///The build cannot be continued..
        /// </summary>
        internal static string BuildError_error_occured {
            get {
                return ResourceManager.GetString("BuildError_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file:
        ///{0}
        ///does not exist, the build operation cannot be continued..
        /// </summary>
        internal static string BuildError_Fie_DoesNotExist {
            get {
                return ResourceManager.GetString("BuildError_Fie_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file:
        ///{0}
        ///does not exist. Do you want to create blank file?.
        /// </summary>
        internal static string BuildError_Fie_DoesNotExist_doyouwanttocreateone {
            get {
                return ResourceManager.GetString("BuildError_Fie_DoesNotExist_doyouwanttocreateone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The build operation cannot be continued..
        /// </summary>
        internal static string BuildError_nocontinuation {
            get {
                return ResourceManager.GetString("BuildError_nocontinuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes to the configuration may be available after restart of the application. It is suggested to restart the application now..
        /// </summary>
        internal static string ConfigurationForm_MessageAfterChange {
            get {
                return ResourceManager.GetString("ConfigurationForm_MessageAfterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigurationFormName {
            get {
                return ResourceManager.GetString("ConfigurationFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Do you want to continue? (All changes will be lost.).
        /// </summary>
        internal static string ConfigurationManagementQuestionAboutContinuationIfChangesArePresent {
            get {
                return ResourceManager.GetString("ConfigurationManagementQuestionAboutContinuationIfChangesArePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string ConfigurationManagementQuestionAboutContinuationIfChangesArePresentTitle {
            get {
                return ResourceManager.GetString("ConfigurationManagementQuestionAboutContinuationIfChangesArePresentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ....
        /// </summary>
        internal static string ConfigurationWrapper_Configuration_Edit_Text {
            get {
                return ResourceManager.GetString("ConfigurationWrapper_Configuration_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens dialog window to edit this instance node configuration and bind 
        ///it to real-time process data sources. Many redundant sources can be defined..
        /// </summary>
        internal static string ConfigurationWrapper_Configuration_Edit_ToolTip {
            get {
                return ResourceManager.GetString("ConfigurationWrapper_Configuration_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ConfigurationWrapper_Configuration_New_Text {
            get {
                return ResourceManager.GetString("ConfigurationWrapper_Configuration_New_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new empty process data bindings configuration for this instance 
        ///node to store proprietary information of the UA server..
        /// </summary>
        internal static string ConfigurationWrapper_Configuration_New_ToolTip {
            get {
                return ResourceManager.GetString("ConfigurationWrapper_Configuration_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: process bindings.
        /// </summary>
        internal static string ConfigurationWrapper_Configuration_Text {
            get {
                return ResourceManager.GetString("ConfigurationWrapper_Configuration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to get more options to manage the real-time process bindings 
        ///of the selected instance..
        /// </summary>
        internal static string ConfigurationWrapper_Configuration_ToolTip {
            get {
                return ResourceManager.GetString("ConfigurationWrapper_Configuration_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(ProjectFileName).csv.
        /// </summary>
        internal static string DefaultCSVFileName {
            get {
                return ResourceManager.GetString("DefaultCSVFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(ProjectFileName).
        /// </summary>
        internal static string DefaultOutputBuildDirectory {
            get {
                return ResourceManager.GetString("DefaultOutputBuildDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model_.
        /// </summary>
        internal static string DefaultProjectName {
            get {
                return ResourceManager.GetString("DefaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution1.
        /// </summary>
        internal static string DefaultSolutionName {
            get {
                return ResourceManager.GetString("DefaultSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoupledNodes.
        /// </summary>
        internal static string DictionaryTreeNode_CoupledNodes {
            get {
                return ResourceManager.GetString("DictionaryTreeNode_CoupledNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node cannot be exported because it does not contain any child nodes or it is not a OPC UA node.
        /// </summary>
        internal static string ExportTool_cannot_expot_wrong_node {
            get {
                return ResourceManager.GetString("ExportTool_cannot_expot_wrong_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application is associated with the specified file for this operation. 
        ///Please associate a default application with this type of file..
        /// </summary>
        internal static string ExportTool_NoDefualtApplication {
            get {
                return ResourceManager.GetString("ExportTool_NoDefualtApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No node is selected..
        /// </summary>
        internal static string ExportTool_NoNodeIsSelected {
            get {
                return ResourceManager.GetString("ExportTool_NoNodeIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Export.
        /// </summary>
        internal static string ExportTool_Window_Name {
            get {
                return ResourceManager.GetString("ExportTool_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi CommServer Team, 
        ///I am interested in the following feature: [{0}]. .
        /// </summary>
        internal static string FeatureRequest_Email_Body {
            get {
                return ResourceManager.GetString("FeatureRequest_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, 
        ///I am interested in the following feature or  the following elements should be changed:
        ///.
        /// </summary>
        internal static string FeatureRequest_Email_Body_Comments {
            get {
                return ResourceManager.GetString("FeatureRequest_Email_Body_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA Address Space Model Designer feature request.
        /// </summary>
        internal static string FeatureRequest_Email_Subject {
            get {
                return ResourceManager.GetString("FeatureRequest_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA Address Space Model Designer comments.
        /// </summary>
        internal static string FeatureRequest_Email_Subject_Comments {
            get {
                return ResourceManager.GetString("FeatureRequest_Email_Subject_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commserver@cas.eu.
        /// </summary>
        internal static string FeatureRequest_EmailAddress {
            get {
                return ResourceManager.GetString("FeatureRequest_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected [{0}] feature is unavailable now, it is under development on our route map.
        ///
        ///Feature additional information: {1}
        ///
        ///If you are interested in this feature, please inform us by sending email.Your default email client will be used to sent this message. 
        ///You can change the message and add more comment but please do not remove the feature name..
        /// </summary>
        internal static string FeatureRequest_MessageBox_Body {
            get {
                return ResourceManager.GetString("FeatureRequest_MessageBox_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature unavailable.
        /// </summary>
        internal static string FeatureRequest_MessageBox_Caption {
            get {
                return ResourceManager.GetString("FeatureRequest_MessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilterHS {
            get {
                object obj = ResourceManager.GetObject("FilterHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FloppyDisk {
            get {
                object obj = ResourceManager.GetObject("FloppyDisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred during installation of example solution:
        ///&quot;{0}&quot;
        ///Example solution is not installed but application will run normally..
        /// </summary>
        internal static string InstalationOfExampleSolutionException {
            get {
                return ResourceManager.GetString("InstalationOfExampleSolutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature is unavailable because your license does not include this functionality..
        /// </summary>
        internal static string LicenseFeatureUnavailable {
            get {
                return ResourceManager.GetString("LicenseFeatureUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while compiling the solution: {0}.
        /// </summary>
        internal static string MainBuildError {
            get {
                return ResourceManager.GetString("MainBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build solution.
        /// </summary>
        internal static string MainBuildErrorLabel {
            get {
                return ResourceManager.GetString("MainBuildErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default application that opens:
        ///{0} 
        ///may be mis-configured 
        ///(details: {1}). 
        ///Please navigate to: {0} manually..
        /// </summary>
        internal static string MainForm_DefaultAppMissing {
            get {
                return ResourceManager.GetString("MainForm_DefaultAppMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseNotes.html.
        /// </summary>
        internal static string MainForm_ReadmePage {
            get {
                return ResourceManager.GetString("MainForm_ReadmePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://commsvr-com.github.io/Documentation/OPCUAebook.
        /// </summary>
        internal static string MainForm_ReadmePage_mainframe {
            get {
                return ResourceManager.GetString("MainForm_ReadmePage_mainframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open solution file because of error: {0}.
        /// </summary>
        internal static string MainForm_StartupExceptionMessage {
            get {
                return ResourceManager.GetString("MainForm_StartupExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/tabid/85/language/en-US/Default.aspx.
        /// </summary>
        internal static string MainForm_TechnicalSupportPage {
            get {
                return ResourceManager.GetString("MainForm_TechnicalSupportPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string MainForm_Title_ChangesArePresent {
            get {
                return ResourceManager.GetString("MainForm_Title_ChangesArePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot install license. Reason: {0}.
        /// </summary>
        internal static string MainProgram_LicenseInstalation_Failure {
            get {
                return ResourceManager.GetString("MainProgram_LicenseInstalation_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License instalation..
        /// </summary>
        internal static string MainProgram_LicenseInstalation_Failure_Caption {
            get {
                return ResourceManager.GetString("MainProgram_LicenseInstalation_Failure_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS OPC UA Address Space Model Designer.
        /// </summary>
        internal static string MainWindowName {
            get {
                return ResourceManager.GetString("MainWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides more options to manage and edit configuration file used by 
        ///the selected  plug-in to save configuration proprietary information of the UA server..
        /// </summary>
        internal static string Menu_UAServer_ToolTipp {
            get {
                return ResourceManager.GetString("Menu_UAServer_ToolTipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality works only when Model View is selected.
        ///Please select Model View..
        /// </summary>
        internal static string MianWindow_FunctionalityAvailiableOnlyInModelView {
            get {
                return ResourceManager.GetString("MianWindow_FunctionalityAvailiableOnlyInModelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not available. Please upgrade your license to Address Space Model Desinger Professional edition..
        /// </summary>
        internal static string ModelDesignerProLicenseWarning {
            get {
                return ResourceManager.GetString("ModelDesignerProLicenseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ns.
        /// </summary>
        internal static string NamespaceFolderCharacterNamespacePrefix_XMLatTheBeginningReplacement {
            get {
                return ResourceManager.GetString("NamespaceFolderCharacterNamespacePrefix_XMLatTheBeginningReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ,.-_&apos;&quot;(){}[]\|/?&gt;&lt;!#@#$%^&amp;*=+.
        /// </summary>
        internal static string NamespaceFolderCharacterToBeRemovedFromNamespacePrefix {
            get {
                return ResourceManager.GetString("NamespaceFolderCharacterToBeRemovedFromNamespacePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string NodeClasses_Children {
            get {
                return ResourceManager.GetString("NodeClasses_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string NodeClasses_ChildrenFolder {
            get {
                return ResourceManager.GetString("NodeClasses_ChildrenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model(Domain).
        /// </summary>
        internal static string NodeClasses_Model {
            get {
                return ResourceManager.GetString("NodeClasses_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string NodeClasses_Namespace {
            get {
                return ResourceManager.GetString("NodeClasses_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamespacesFolder.
        /// </summary>
        internal static string NodeClasses_NamespaceFolder {
            get {
                return ResourceManager.GetString("NodeClasses_NamespaceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string NodeClasses_Objects_Dictionary {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string NodeClasses_Objects_Encoding {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EncodingsFolder.
        /// </summary>
        internal static string NodeClasses_Objects_EncodingsFolder {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_EncodingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string NodeClasses_Objects_Instance {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string NodeClasses_Objects_Method {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string NodeClasses_Objects_Node {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string NodeClasses_Objects_Object {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string NodeClasses_Objects_Parameter {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParametersFolder.
        /// </summary>
        internal static string NodeClasses_Objects_ParametersFolder {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_ParametersFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string NodeClasses_Objects_Property {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string NodeClasses_Objects_Reference {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferencesFolder.
        /// </summary>
        internal static string NodeClasses_Objects_ReferencesFolder {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_ReferencesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string NodeClasses_Objects_Variable {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string NodeClasses_Objects_View {
            get {
                return ResourceManager.GetString("NodeClasses_Objects_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType.
        /// </summary>
        internal static string NodeClasses_Types_DataType {
            get {
                return ResourceManager.GetString("NodeClasses_Types_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventType.
        /// </summary>
        internal static string NodeClasses_Types_EventType {
            get {
                return ResourceManager.GetString("NodeClasses_Types_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectType.
        /// </summary>
        internal static string NodeClasses_Types_ObjectType {
            get {
                return ResourceManager.GetString("NodeClasses_Types_ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceType.
        /// </summary>
        internal static string NodeClasses_Types_ReferenceType {
            get {
                return ResourceManager.GetString("NodeClasses_Types_ReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachineType.
        /// </summary>
        internal static string NodeClasses_Types_StateMachineType {
            get {
                return ResourceManager.GetString("NodeClasses_Types_StateMachineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string NodeClasses_Types_Type {
            get {
                return ResourceManager.GetString("NodeClasses_Types_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VariableType.
        /// </summary>
        internal static string NodeClasses_Types_VariableType {
            get {
                return ResourceManager.GetString("NodeClasses_Types_VariableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string NodeSet_FileDialogDefaultExt {
            get {
                return ResourceManager.GetString("NodeSet_FileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeSet Model File (* .xml)|*.xml|All files(*.*)|*.*.
        /// </summary>
        internal static string NodeSet_FileDialogFilter {
            get {
                return ResourceManager.GetString("NodeSet_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA NodeSet Model Import dialog window.
        /// </summary>
        internal static string NodeSet_FileDialogTitle {
            get {
                return ResourceManager.GetString("NodeSet_FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while importing model from NodeSet file: {0}.
        /// </summary>
        internal static string NodeSet_ImportErrorMessage {
            get {
                return ResourceManager.GetString("NodeSet_ImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeSet import error.
        /// </summary>
        internal static string NodeSet_ImportErrorTitle {
            get {
                return ResourceManager.GetString("NodeSet_ImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectsFolder.
        /// </summary>
        internal static string ObjectsFolderXmlQualifiedNameName {
            get {
                return ResourceManager.GetString("ObjectsFolderXmlQualifiedNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error occurred during opening the  file. Maybe you are trying to open model file as a solution?
        ///See reason below to find a solution for this issue:
        ///{0}.
        /// </summary>
        internal static string OPCFSolutionConfigurationManagement_ReadError {
            get {
                return ResourceManager.GetString("OPCFSolutionConfigurationManagement_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model compiler application calling arguments. .
        /// </summary>
        internal static string OptionDescription_Build_ProjectCompilationString {
            get {
                return ResourceManager.GetString("OptionDescription_Build_ProjectCompilationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates, if the coupled nodes in Model View appears on the model tree..
        /// </summary>
        internal static string OptionDescription_CoupledNodesAreEnabled {
            get {
                return ResourceManager.GetString("OptionDescription_CoupledNodesAreEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the default name of the solution..
        /// </summary>
        internal static string OptionDescription_DefaultSolutionFileName {
            get {
                return ResourceManager.GetString("OptionDescription_DefaultSolutionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of font used in the application. Minimum size is 6 points and maximum size is 18 points..
        /// </summary>
        internal static string OptionDescription_FontSize {
            get {
                return ResourceManager.GetString("OptionDescription_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the file, that contains information about all topics in UA e-book..
        /// </summary>
        internal static string OptionDescription_HelpDocumentationAllTopicsFileName {
            get {
                return ResourceManager.GetString("OptionDescription_HelpDocumentationAllTopicsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of the file, that contains information about all topics in UA e-book..
        /// </summary>
        internal static string OptionDescription_HelpDocumentationAllTopicsWebAddress {
            get {
                return ResourceManager.GetString("OptionDescription_HelpDocumentationAllTopicsWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC UA e-book web address..
        /// </summary>
        internal static string OptionDescription_HelpDocumentationOpcUaEbookURL {
            get {
                return ResourceManager.GetString("OptionDescription_HelpDocumentationOpcUaEbookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix for the address of topics in OPC UA e-book..
        /// </summary>
        internal static string OptionDescription_HelpDocumentationURLsuffix {
            get {
                return ResourceManager.GetString("OptionDescription_HelpDocumentationURLsuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates, if  ModelView tree is synchronized with the UA e-book. If the value is &quot;true&quot;, then after clicking on the ModelView node, in Help panel, the proper site from OPC UA e-book appears..
        /// </summary>
        internal static string OptionDescription_HelpSynchronizationIsEnabled {
            get {
                return ResourceManager.GetString("OptionDescription_HelpSynchronizationIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the project compiler executable file..
        /// </summary>
        internal static string OptionDescription_ProjectCompilationExecutable {
            get {
                return ResourceManager.GetString("OptionDescription_ProjectCompilationExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory, where the sample solution is being installed..
        /// </summary>
        internal static string OptionDescription_SampleInstallationDirectory {
            get {
                return ResourceManager.GetString("OptionDescription_SampleInstallationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates, if the sample solution is installed..
        /// </summary>
        internal static string OptionDescription_SampleIsInstalled {
            get {
                return ResourceManager.GetString("OptionDescription_SampleIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace for the project..
        /// </summary>
        internal static string OptionDescription_TargetNamespace {
            get {
                return ResourceManager.GetString("OptionDescription_TargetNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target namespace XML prefix.
        /// </summary>
        internal static string OptionDescription_TargetNamespaceXmlPrefix {
            get {
                return ResourceManager.GetString("OptionDescription_TargetNamespaceXmlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML target namespace for the project.
        /// </summary>
        internal static string OptionDescription_TargetXmlNamespace {
            get {
                return ResourceManager.GetString("OptionDescription_TargetXmlNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace for OPC types..
        /// </summary>
        internal static string OptionDescription_XmlOPCTypesNamespace {
            get {
                return ResourceManager.GetString("OptionDescription_XmlOPCTypesNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix for OPCtypes namespace..
        /// </summary>
        internal static string OptionDescription_XmlOPCTypesPrefix {
            get {
                return ResourceManager.GetString("OptionDescription_XmlOPCTypesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace for XML schema instance..
        /// </summary>
        internal static string OptionDescription_XmlSchemaInstanceNamespace {
            get {
                return ResourceManager.GetString("OptionDescription_XmlSchemaInstanceNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix for XML schema instance..
        /// </summary>
        internal static string OptionDescription_XmlSchemaInstancePrefix {
            get {
                return ResourceManager.GetString("OptionDescription_XmlSchemaInstancePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML schema namespace for the model..
        /// </summary>
        internal static string OptionDescription_XmlSchemaNamespace {
            get {
                return ResourceManager.GetString("OptionDescription_XmlSchemaNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix of the XML schema namespace for the model..
        /// </summary>
        internal static string OptionDescription_XmlSchemaPrefix {
            get {
                return ResourceManager.GetString("OptionDescription_XmlSchemaPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML namespace for UA types.
        /// </summary>
        internal static string OptionDescription_XmlUATypesNamespace {
            get {
                return ResourceManager.GetString("OptionDescription_XmlUATypesNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix for XML namespace for UA types.
        /// </summary>
        internal static string OptionDescription_XmlUATypesPrefix {
            get {
                return ResourceManager.GetString("OptionDescription_XmlUATypesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with opening of the description for option. The error message is: .
        /// </summary>
        internal static string ProblemWithDescriptionForOption {
            get {
                return ResourceManager.GetString("ProblemWithDescriptionForOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table cannot be dispalyed.
        /// </summary>
        internal static string ProblemwithDisplayingStateMachine_Info {
            get {
                return ResourceManager.GetString("ProblemwithDisplayingStateMachine_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with opening state machine.
        /// </summary>
        internal static string ProblemWithStateMachine_Header {
            get {
                return ResourceManager.GetString("ProblemWithStateMachine_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node doesn&apos;t represent a state machine or it is empty!.
        /// </summary>
        internal static string ProblemWithStateMachine_Info {
            get {
                return ResourceManager.GetString("ProblemWithStateMachine_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start {0} (reason: {1})..
        /// </summary>
        internal static string ProcessStart_Exception {
            get {
                return ResourceManager.GetString("ProcessStart_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string Project_FileDialogDefaultExt {
            get {
                return ResourceManager.GetString("Project_FileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAModelDesignerProject.xml.
        /// </summary>
        internal static string Project_FileDialogDefaultFilename {
            get {
                return ResourceManager.GetString("Project_FileDialogDefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Model File (* .xml)|*.xml|All files(*.*)|*.*.
        /// </summary>
        internal static string Project_FileDialogFilter {
            get {
                return ResourceManager.GetString("Project_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA Model Designer Project or Model Open/Save dialog window.
        /// </summary>
        internal static string Project_FileDialogTitle {
            get {
                return ResourceManager.GetString("Project_FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while reading data from the project file: {0}.
        /// </summary>
        internal static string Project_FileOpenError {
            get {
                return ResourceManager.GetString("Project_FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project file.
        /// </summary>
        internal static string Project_OpenFileCaption {
            get {
                return ResourceManager.GetString("Project_OpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file not found!.
        /// </summary>
        internal static string ProjectFileNotFound_Header {
            get {
                return ResourceManager.GetString("ProjectFileNotFound_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file: {0} has not been found..
        /// </summary>
        internal static string ProjectFileNotFound_Info {
            get {
                return ResourceManager.GetString("ProjectFileNotFound_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ProjectTreeNode {
            get {
                return ResourceManager.GetString("ProjectTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project removal..
        /// </summary>
        internal static string ProjectTreeNode_AreYouSureToRemove_caption {
            get {
                return ResourceManager.GetString("ProjectTreeNode_AreYouSureToRemove_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove project: {0} ?.
        /// </summary>
        internal static string ProjectTreeNode_AreYouSureToRemove_text {
            get {
                return ResourceManager.GetString("ProjectTreeNode_AreYouSureToRemove_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://opcfoundation.org/UA/:HasComponent.
        /// </summary>
        internal static string ReferenceHasComponentXmlQualifiedName {
            get {
                return ResourceManager.GetString("ReferenceHasComponentXmlQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be found..
        /// </summary>
        internal static string Search_cannotbefound {
            get {
                return ResourceManager.GetString("Search_cannotbefound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search has passed end of the tree, searching is continued  from the beginning..
        /// </summary>
        internal static string Search_endispassed {
            get {
                return ResourceManager.GetString("Search_endispassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search has passed beginning  of the tree,  searching is continued  from the end..
        /// </summary>
        internal static string Search_startispassed {
            get {
                return ResourceManager.GetString("Search_startispassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uamdsl.
        /// </summary>
        internal static string Solution_FileDialogDefaultExt {
            get {
                return ResourceManager.GetString("Solution_FileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAModelDesignerSolution.uamdsl.
        /// </summary>
        internal static string Solution_FileDialogDefaultFilename {
            get {
                return ResourceManager.GetString("Solution_FileDialogDefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA Model Designer Solution File (* .uamdsl)|*.uamdsl|UA Model Designer Solution File (* .xml)|*.xml|All files(*.*)|*.*.
        /// </summary>
        internal static string Solution_FileDialogFilter {
            get {
                return ResourceManager.GetString("Solution_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA Model Designer Solution Open/Save dialog window.
        /// </summary>
        internal static string Solution_FileDialogTitle {
            get {
                return ResourceManager.GetString("Solution_FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution File Open Error.
        /// </summary>
        internal static string SolutionFileOpenError {
            get {
                return ResourceManager.GetString("SolutionFileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution File Save Error.
        /// </summary>
        internal static string SolutionFileSaveError {
            get {
                return ResourceManager.GetString("SolutionFileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SolutionTreeNode {
            get {
                return ResourceManager.GetString("SolutionTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreen {
            get {
                object obj = ResourceManager.GetObject("SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your evaluation period has just expired.  You must purchase the commercial license to use this software. 
        ///To get more press the “Buy Now” button.  
        ///To start {0} in read only mode press “Start” button.    .
        /// </summary>
        internal static string SplashScreenLicenseDemoPeriodExpired {
            get {
                return ResourceManager.GetString("SplashScreenLicenseDemoPeriodExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon StateMachineIcon {
            get {
                object obj = ResourceManager.GetObject("StateMachineIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(ProjectFileName).
        /// </summary>
        internal static string Token_ProjectFileName {
            get {
                return ResourceManager.GetString("Token_ProjectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transition {
            get {
                object obj = ResourceManager.GetObject("transition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the file.
        ///Reason:
        ///{0}.
        /// </summary>
        internal static string TypeGenericConfigurationManagement_ReadError {
            get {
                return ResourceManager.GetString("TypeGenericConfigurationManagement_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is problem during obtaining the type list..
        /// </summary>
        internal static string VariableValueEditorTypeList_problem {
            get {
                return ResourceManager.GetString("VariableValueEditorTypeList_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add node ....
        /// </summary>
        internal static string WrapperTreeNode_menu_add_object {
            get {
                return ResourceManager.GetString("WrapperTreeNode_menu_add_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string WrapperTreeNode_menu_copy {
            get {
                return ResourceManager.GetString("WrapperTreeNode_menu_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string WrapperTreeNode_menu_cut {
            get {
                return ResourceManager.GetString("WrapperTreeNode_menu_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element cannot be &quot;Cut&quot;, but its content is stored in the clipboard..
        /// </summary>
        internal static string WrapperTreeNode_menu_cut_cannot_be_cut {
            get {
                return ResourceManager.GetString("WrapperTreeNode_menu_cut_cannot_be_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string WrapperTreeNode_menu_delete {
            get {
                return ResourceManager.GetString("WrapperTreeNode_menu_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string WrapperTreeNode_menu_paste {
            get {
                return ResourceManager.GetString("WrapperTreeNode_menu_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Paste&quot; cannot be performed for this node or for the current content of the clipboard..
        /// </summary>
        internal static string WrapperTreeNode_menu_paste_cannot_be_done {
            get {
                return ResourceManager.GetString("WrapperTreeNode_menu_paste_cannot_be_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoTo: .
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Type.
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto_BaseType {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto_BaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Base Type node and go to that node.
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto_BaseType_tooltip {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto_BaseType_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType.
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto_DataType {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Data Type node and go to that node.
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto_DataType_tooltip {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto_DataType_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type.
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto_ReferenceType {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto_ReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto_Target {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Definition.
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto_TypeDefinition {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto_TypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Type Definition node and go to that node.
        /// </summary>
        internal static string WrapperTreeNodeAddMenuItemGoto_TypeDefinition_tooltip {
            get {
                return ResourceManager.GetString("WrapperTreeNodeAddMenuItemGoto_TypeDefinition_tooltip", resourceCulture);
            }
        }
    }
}
