//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.UA.Model.Designer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UAModelDesignerSolution")]
        public string DefaultSolutionFileName {
            get {
                return ((string)(this["DefaultSolutionFileName"]));
            }
            set {
                this["DefaultSolutionFileName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("allTopics.xml")]
        public string HelpDocumentationAllTopicsFileName {
            get {
                return ((string)(this["HelpDocumentationAllTopicsFileName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public float FontSize {
            get {
                return ((float)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CoupledNodesAreEnabled {
            get {
                return ((bool)(this["CoupledNodesAreEnabled"]));
            }
            set {
                this["CoupledNodesAreEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HelpSynchronizationIsEnabled {
            get {
                return ((bool)(this["HelpSynchronizationIsEnabled"]));
            }
            set {
                this["HelpSynchronizationIsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UAAddressSpaceModelDesigner\\Sample")]
        public string SampleInstallationDirectory {
            get {
                return ((string)(this["SampleInstallationDirectory"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://opcfoundation.org/UA/2008/02/Types.xsd")]
        public string XmlUATypesNamespace {
            get {
                return ((string)(this["XmlUATypesNamespace"]));
            }
            set {
                this["XmlUATypesNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ua")]
        public string XmlUATypesPrefix {
            get {
                return ((string)(this["XmlUATypesPrefix"]));
            }
            set {
                this["XmlUATypesPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-d2 \"{0}\"  -cg \"{1}\" -o \"{2}\" -console")]
        public string Build_ProjectCompilationString {
            get {
                return ((string)(this["Build_ProjectCompilationString"]));
            }
            set {
                this["Build_ProjectCompilationString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("exe\\CAS.CommServer.UA.ModelCompiler.Command.exe")]
        public string ProjectCompilationExecutable {
            get {
                return ((string)(this["ProjectCompilationExecutable"]));
            }
            set {
                this["ProjectCompilationExecutable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cas")]
        public string TargetNamespaceXmlPrefix {
            get {
                return ((string)(this["TargetNamespaceXmlPrefix"]));
            }
            set {
                this["TargetNamespaceXmlPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.w3.org/2001/XMLSchema-instance")]
        public string XmlSchemaInstanceNamespace {
            get {
                return ((string)(this["XmlSchemaInstanceNamespace"]));
            }
            set {
                this["XmlSchemaInstanceNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xsi")]
        public string XmlSchemaInstancePrefix {
            get {
                return ((string)(this["XmlSchemaInstancePrefix"]));
            }
            set {
                this["XmlSchemaInstancePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.w3.org/2001/XMLSchema")]
        public string XmlSchemaNamespace {
            get {
                return ((string)(this["XmlSchemaNamespace"]));
            }
            set {
                this["XmlSchemaNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xsd")]
        public string XmlSchemaPrefix {
            get {
                return ((string)(this["XmlSchemaPrefix"]));
            }
            set {
                this["XmlSchemaPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://opcfoundation.org/UA/2008/02/Types.xsd")]
        public string XmlOPCTypesNamespace {
            get {
                return ((string)(this["XmlOPCTypesNamespace"]));
            }
            set {
                this["XmlOPCTypesNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uax")]
        public string XmlOPCTypesPrefix {
            get {
                return ((string)(this["XmlOPCTypesPrefix"]));
            }
            set {
                this["XmlOPCTypesPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cas.eu/UA/CommServer/")]
        public string TargetNamespace {
            get {
                return ((string)(this["TargetNamespace"]));
            }
            set {
                this["TargetNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cas.eu/UA/CommServer/")]
        public string TargetXmlNamespace {
            get {
                return ((string)(this["TargetXmlNamespace"]));
            }
            set {
                this["TargetXmlNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaintenancePeriodWarning {
            get {
                return ((bool)(this["MaintenancePeriodWarning"]));
            }
            set {
                this["MaintenancePeriodWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CAS.CommServer.ModelDesigner.OPCViewer.exe")]
        public string OPCViewerAssemblyName {
            get {
                return ((string)(this["OPCViewerAssemblyName"]));
            }
            set {
                this["OPCViewerAssemblyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OnlyItemsInAddressSpace {
            get {
                return ((bool)(this["OnlyItemsInAddressSpace"]));
            }
            set {
                this["OnlyItemsInAddressSpace"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://commsvr-com.github.io/Documentation/OPCUAebook/")]
        public string HelpDocumentationOpcUaEbookURL {
            get {
                return ((string)(this["HelpDocumentationOpcUaEbookURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HelpDocumentationURLsuffix {
            get {
                return ((string)(this["HelpDocumentationURLsuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://commsvr-com.github.io/Documentation/OPCUAebook/allTopics.xml")]
        public string HelpDocumentationAllTopicsWebAddress {
            get {
                return ((string)(this["HelpDocumentationAllTopicsWebAddress"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://opcfoundation.org/UA/")]
        public string XmlUANamespaceURI {
            get {
                return ((string)(this["XmlUANamespaceURI"]));
            }
            set {
                this["XmlUANamespaceURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OpcUa")]
        public string XmlUAName {
            get {
                return ((string)(this["XmlUAName"]));
            }
            set {
                this["XmlUAName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Opc.Ua")]
        public string XmlUAPrefix {
            get {
                return ((string)(this["XmlUAPrefix"]));
            }
            set {
                this["XmlUAPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("log")]
        public string LogFolder {
            get {
                return ((string)(this["LogFolder"]));
            }
            set {
                this["LogFolder"] = value;
            }
        }
    }
}
