//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.UA.Model.Designer.Wrappers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WrapperResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WrapperResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAS.UA.Model.Designer.Wrappers.WrapperResources", typeof(WrapperResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string ChildrenFolderText {
            get {
                return ResourceManager.GetString("ChildrenFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the base node for all Instance Nodes (Object, Variable, 
        ///Properties and Method)..
        /// </summary>
        internal static string ChildrenFolderToolTip {
            get {
                return ResourceManager.GetString("ChildrenFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string DataTypeParametersNodeText {
            get {
                return ResourceManager.GetString("DataTypeParametersNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder contains a collection of all human readable values for 
        /// the enumeration DataType..
        /// </summary>
        internal static string DataTypeParametersNodeTipText {
            get {
                return ResourceManager.GetString("DataTypeParametersNodeTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete address space node..
        /// </summary>
        internal static string DeleteObjectCaption {
            get {
                return ResourceManager.GetString("DeleteObjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the node {0} ({1}). Are you sure?.
        /// </summary>
        internal static string DeleteObjectWarning {
            get {
                return ResourceManager.GetString("DeleteObjectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder contains a collection of all human readable values 
        ///for the enumeration DataType..
        /// </summary>
        internal static string FildsFolderNodeToolTipText {
            get {
                return ResourceManager.GetString("FildsFolderNodeToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder container organizes the address space..
        /// </summary>
        internal static string FolderTooStripToolText {
            get {
                return ResourceManager.GetString("FolderTooStripToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main container of all the objects defined in the namespace: {0}.
        ///It is the root element for the information model. This container allows information modelers
        ///to define UA types and objects. This definition can be used to generate code and documentation..
        /// </summary>
        internal static string ModelDesignNodeToolTipText {
            get {
                return ResourceManager.GetString("ModelDesignNodeToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces collection defined for the model..
        /// </summary>
        internal static string NamespaceFolderToolTipText {
            get {
                return ResourceManager.GetString("NamespaceFolderToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        internal static string ParametersFolderInputTreeNodeText {
            get {
                return ResourceManager.GetString("ParametersFolderInputTreeNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input arguments collection..
        /// </summary>
        internal static string ParametersFolderInputTreeNodeToolTipText {
            get {
                return ResourceManager.GetString("ParametersFolderInputTreeNodeToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        internal static string ParametersFolderOutputTreeNodeText {
            get {
                return ResourceManager.GetString("ParametersFolderOutputTreeNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output arguments collection..
        /// </summary>
        internal static string ParametersFolderOutputTreeNodeToolTipText {
            get {
                return ResourceManager.GetString("ParametersFolderOutputTreeNodeToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References collection defined for the parent object.
        ///The References specify additional references from the Node..
        /// </summary>
        internal static string ReferencesFolderNodeToolTipText {
            get {
                return ResourceManager.GetString("ReferencesFolderNodeToolTipText", resourceCulture);
            }
        }
    }
}
